---
sudo: false
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake test"
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.2
    env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES="yes"
notifications:
  email: true
  irc:
    channels:
      - "irc.msi.umn.edu#iops"
    on_success: change
    on_failure: always
    skip_join: true
